/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import java.awt.Toolkit;

/**
 *
 * @author pc
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    double num, ans, answer;
    int calculation;
    
    public Calculator() {
        initComponents();
        setIcon();
        disable();
    }
    public void arithmetic_operation(){
        switch(calculation){
            case 1: 
                ans = num + Double.parseDouble(jTFDisplay.getText());
                jTFDisplay.setText(Double.toString(ans));
                break;
            case 2: 
                ans = num - Double.parseDouble(jTFDisplay.getText());
                jTFDisplay.setText(Double.toString(ans));
                break;
            case 3: 
                ans = num * Double.parseDouble(jTFDisplay.getText());
                jTFDisplay.setText(Double.toString(ans));
                break;
            case 4: 
                ans = num / Double.parseDouble(jTFDisplay.getText());
                jTFDisplay.setText(Double.toString(ans));
                break;
            case 5: 
                ans = num % Double.parseDouble(jTFDisplay.getText());
                jTFDisplay.setText(Double.toString(ans));
                break; 
            case 6:
                ans = num *10;
                jTFDisplay.setText(Double.toString(ans));
            case 7:
                jTFDisplay.setText(jTFOperation.getText());
                jTFOperation.setText("");
        }
    }
       public void enable() {
        jRadioBOn.setEnabled(false);
        jRadioOff.setEnabled(true);
        jBMood.setEnabled(true);
       jBSqrt.setEnabled(true);
       jBPowerOf2.setEnabled(true);
       jBPowerOf3.setEnabled(true);
       jBPowerOfX.setEnabled(true);
       jBSeven.setEnabled(true);
       jBEight.setEnabled(true);
       jBNine.setEnabled(true);
       jBDevision.setEnabled(true);
       jBClear.setEnabled(true);
       jBFour.setEnabled(true);
       jBFive.setEnabled(true);
       jBSix.setEnabled(true);
       jBMultiplication.setEnabled(true);
       jBDelete.setEnabled(true);
       jBOne.setEnabled(true);
       jBTwo.setEnabled(true);
       jBThree.setEnabled(true);
       jBSubstraction.setEnabled(true);
       jBSign.setEnabled(true);
       jBZero.setEnabled(true);
       jBDote.setEnabled(true);
       jBMultipleTen.setEnabled(true);
       JBPlus.setEnabled(true);
       jBEqual.setEnabled(true);
       jBBinary.setEnabled(true);
       jBHexdecimal.setEnabled(true);
       jBSin.setEnabled(true);
       jBCos.setEnabled(true);
       jBTan.setEnabled(true);
    }
   public void disable(){
       
       jRadioBOn.setEnabled(true);
       jRadioOff.setEnabled(false);
       jBMood.setEnabled(false);
       jBSqrt.setEnabled(false);
       jBPowerOf2.setEnabled(false);
       jBPowerOf3.setEnabled(false);
       jBPowerOfX.setEnabled(false);
       jBSeven.setEnabled(false);
       jBEight.setEnabled(false);
       jBNine.setEnabled(false);
       jBDevision.setEnabled(false);
       jBClear.setEnabled(false);
       jBFour.setEnabled(false);
       jBFive.setEnabled(false);
       jBSix.setEnabled(false);
       jBMultiplication.setEnabled(false);
       jBDelete.setEnabled(false);
       jBOne.setEnabled(false);
       jBTwo.setEnabled(false);
       jBThree.setEnabled(false);
       jBSubstraction.setEnabled(false);
       jBSign.setEnabled(false);
       jBZero.setEnabled(false);
       jBDote.setEnabled(false);
       jBMultipleTen.setEnabled(false);
       JBPlus.setEnabled(false);
       jBEqual.setEnabled(false);
       jBBinary.setEnabled(false);
       jBHexdecimal.setEnabled(false);
       jBSin.setEnabled(false);
       jBCos.setEnabled(false);
       jBTan.setEnabled(false);
       jTFDisplay.setText("");
       jTFOperation.setText("");
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBEqual = new javax.swing.JButton();
        JBPlus = new javax.swing.JButton();
        jBMultipleTen = new javax.swing.JButton();
        jBDote = new javax.swing.JButton();
        jBZero = new javax.swing.JButton();
        jBOne = new javax.swing.JButton();
        jBTwo = new javax.swing.JButton();
        jBFour = new javax.swing.JButton();
        jBSeven = new javax.swing.JButton();
        jBSqrt = new javax.swing.JButton();
        jBMood = new javax.swing.JButton();
        jBEight = new javax.swing.JButton();
        jBFive = new javax.swing.JButton();
        jBSix = new javax.swing.JButton();
        jBThree = new javax.swing.JButton();
        jBSubstraction = new javax.swing.JButton();
        jBSign = new javax.swing.JButton();
        jBDelete = new javax.swing.JButton();
        jBMultiplication = new javax.swing.JButton();
        jBDevision = new javax.swing.JButton();
        jBClear = new javax.swing.JButton();
        jBPowerOfX = new javax.swing.JButton();
        jBPowerOf3 = new javax.swing.JButton();
        jBPowerOf2 = new javax.swing.JButton();
        jBNine = new javax.swing.JButton();
        jRadioOff = new javax.swing.JRadioButton();
        jRadioBOn = new javax.swing.JRadioButton();
        jBBinary = new javax.swing.JButton();
        jBHexdecimal = new javax.swing.JButton();
        jBSin = new javax.swing.JButton();
        jBCos = new javax.swing.JButton();
        jBTan = new javax.swing.JButton();
        jTFDisplay = new javax.swing.JTextField();
        jTFOperation = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        Quit = new javax.swing.JMenu();
        jMenuOpen = new javax.swing.JMenuItem();
        jMenuQuit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(223, 222, 222));

        jBEqual.setBackground(new java.awt.Color(189, 190, 192));
        jBEqual.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBEqual.setText("=");
        jBEqual.setBorder(null);
        jBEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEqualActionPerformed(evt);
            }
        });

        JBPlus.setBackground(new java.awt.Color(189, 190, 192));
        JBPlus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JBPlus.setText("+");
        JBPlus.setBorder(null);
        JBPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPlusActionPerformed(evt);
            }
        });

        jBMultipleTen.setBackground(new java.awt.Color(189, 190, 192));
        jBMultipleTen.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBMultipleTen.setText("x10");
        jBMultipleTen.setBorder(null);
        jBMultipleTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMultipleTenActionPerformed(evt);
            }
        });

        jBDote.setBackground(new java.awt.Color(189, 190, 192));
        jBDote.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBDote.setText(".");
        jBDote.setBorder(null);
        jBDote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDoteActionPerformed(evt);
            }
        });

        jBZero.setBackground(new java.awt.Color(189, 190, 192));
        jBZero.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBZero.setText("0");
        jBZero.setBorder(null);
        jBZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBZeroActionPerformed(evt);
            }
        });

        jBOne.setBackground(new java.awt.Color(189, 190, 192));
        jBOne.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBOne.setText("1");
        jBOne.setBorder(null);
        jBOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOneActionPerformed(evt);
            }
        });

        jBTwo.setBackground(new java.awt.Color(189, 190, 192));
        jBTwo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBTwo.setText("2");
        jBTwo.setBorder(null);
        jBTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTwoActionPerformed(evt);
            }
        });

        jBFour.setBackground(new java.awt.Color(189, 190, 192));
        jBFour.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBFour.setText("4");
        jBFour.setBorder(null);
        jBFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFourActionPerformed(evt);
            }
        });

        jBSeven.setBackground(new java.awt.Color(189, 190, 192));
        jBSeven.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBSeven.setText("7");
        jBSeven.setBorder(null);
        jBSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSevenActionPerformed(evt);
            }
        });

        jBSqrt.setBackground(new java.awt.Color(189, 190, 192));
        jBSqrt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBSqrt.setText("sqrt");
        jBSqrt.setBorder(null);
        jBSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSqrtActionPerformed(evt);
            }
        });

        jBMood.setBackground(new java.awt.Color(189, 190, 192));
        jBMood.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBMood.setText("%");
        jBMood.setBorder(null);
        jBMood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMoodActionPerformed(evt);
            }
        });

        jBEight.setBackground(new java.awt.Color(189, 190, 192));
        jBEight.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBEight.setText("8");
        jBEight.setBorder(null);
        jBEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEightActionPerformed(evt);
            }
        });

        jBFive.setBackground(new java.awt.Color(189, 190, 192));
        jBFive.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBFive.setText("5");
        jBFive.setBorder(null);
        jBFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFiveActionPerformed(evt);
            }
        });

        jBSix.setBackground(new java.awt.Color(189, 190, 192));
        jBSix.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBSix.setText("6");
        jBSix.setBorder(null);
        jBSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSixActionPerformed(evt);
            }
        });

        jBThree.setBackground(new java.awt.Color(189, 190, 192));
        jBThree.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBThree.setText("3");
        jBThree.setBorder(null);
        jBThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBThreeActionPerformed(evt);
            }
        });

        jBSubstraction.setBackground(new java.awt.Color(189, 190, 192));
        jBSubstraction.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBSubstraction.setText("-");
        jBSubstraction.setBorder(null);
        jBSubstraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSubstractionActionPerformed(evt);
            }
        });

        jBSign.setBackground(new java.awt.Color(189, 190, 192));
        jBSign.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBSign.setText("+/-");
        jBSign.setBorder(null);
        jBSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSignActionPerformed(evt);
            }
        });

        jBDelete.setBackground(new java.awt.Color(189, 190, 192));
        jBDelete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBDelete.setText("<--");
        jBDelete.setBorder(null);
        jBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteActionPerformed(evt);
            }
        });

        jBMultiplication.setBackground(new java.awt.Color(189, 190, 192));
        jBMultiplication.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBMultiplication.setText("x");
        jBMultiplication.setBorder(null);
        jBMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMultiplicationActionPerformed(evt);
            }
        });

        jBDevision.setBackground(new java.awt.Color(189, 190, 192));
        jBDevision.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBDevision.setText("/");
        jBDevision.setToolTipText("");
        jBDevision.setBorder(null);
        jBDevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDevisionActionPerformed(evt);
            }
        });

        jBClear.setBackground(new java.awt.Color(189, 190, 192));
        jBClear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBClear.setText("C");
        jBClear.setBorder(null);
        jBClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClearActionPerformed(evt);
            }
        });

        jBPowerOfX.setBackground(new java.awt.Color(189, 190, 192));
        jBPowerOfX.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBPowerOfX.setText("x^x");
        jBPowerOfX.setBorder(null);
        jBPowerOfX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPowerOfXActionPerformed(evt);
            }
        });

        jBPowerOf3.setBackground(new java.awt.Color(189, 190, 192));
        jBPowerOf3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBPowerOf3.setText("x^3");
        jBPowerOf3.setBorder(null);
        jBPowerOf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPowerOf3ActionPerformed(evt);
            }
        });

        jBPowerOf2.setBackground(new java.awt.Color(189, 190, 192));
        jBPowerOf2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBPowerOf2.setText("x^2");
        jBPowerOf2.setBorder(null);
        jBPowerOf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPowerOf2ActionPerformed(evt);
            }
        });

        jBNine.setBackground(new java.awt.Color(189, 190, 192));
        jBNine.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBNine.setText("9");
        jBNine.setBorder(null);
        jBNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNineActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioOff);
        jRadioOff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioOff.setForeground(new java.awt.Color(255, 255, 255));
        jRadioOff.setText("OFF");
        jRadioOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioOffActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioBOn);
        jRadioBOn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioBOn.setForeground(new java.awt.Color(255, 255, 255));
        jRadioBOn.setText("ON");
        jRadioBOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBOnActionPerformed(evt);
            }
        });

        jBBinary.setBackground(new java.awt.Color(189, 190, 192));
        jBBinary.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBBinary.setText("Bin");
        jBBinary.setBorder(null);
        jBBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBinaryActionPerformed(evt);
            }
        });

        jBHexdecimal.setBackground(new java.awt.Color(189, 190, 192));
        jBHexdecimal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBHexdecimal.setText("Hex");
        jBHexdecimal.setBorder(null);
        jBHexdecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHexdecimalActionPerformed(evt);
            }
        });

        jBSin.setBackground(new java.awt.Color(189, 190, 192));
        jBSin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBSin.setText("sin");
        jBSin.setBorder(null);
        jBSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSinActionPerformed(evt);
            }
        });

        jBCos.setBackground(new java.awt.Color(189, 190, 192));
        jBCos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBCos.setText("cos");
        jBCos.setBorder(null);
        jBCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCosActionPerformed(evt);
            }
        });

        jBTan.setBackground(new java.awt.Color(189, 190, 192));
        jBTan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBTan.setText("tan");
        jBTan.setBorder(null);
        jBTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBZero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBDote, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBMultipleTen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jBMood, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBSin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBCos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBTan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jBEight, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jBNine, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jBDevision, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jBClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBFour, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jBFive, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jBSix, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jBMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jBDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBOne, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jBTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jBThree, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jBSubstraction, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jBSign, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioBOn)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioOff)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jBHexdecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBPowerOf2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jBPowerOf3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jBPowerOfX, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioBOn)
                    .addComponent(jRadioOff))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBHexdecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPowerOf2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPowerOf3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPowerOfX, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBMood, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBSin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBCos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBTan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEight, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBNine, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDevision, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBFour, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFive, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSix, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBOne, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBThree, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSubstraction, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSign, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBZero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDote, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMultipleTen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTFDisplay.setEditable(false);
        jTFDisplay.setBackground(new java.awt.Color(255, 255, 255));
        jTFDisplay.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTFDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFDisplay.setBorder(null);
        jTFDisplay.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTFDisplay.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTFDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDisplayActionPerformed(evt);
            }
        });

        jTFOperation.setEditable(false);
        jTFOperation.setBackground(new java.awt.Color(255, 255, 255));
        jTFOperation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTFOperation.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFOperation.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFDisplay)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jTFOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Quit.setText("File");

        jMenuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuOpen.setText("Open");
        jMenuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOpenActionPerformed(evt);
            }
        });
        Quit.add(jMenuOpen);

        jMenuQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuQuit.setText("Quit");
        jMenuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuitActionPerformed(evt);
            }
        });
        Quit.add(jMenuQuit);

        jMenuBar1.add(Quit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOpenActionPerformed
        enable();
    }//GEN-LAST:event_jMenuOpenActionPerformed

    private void jMenuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuQuitActionPerformed

    private void jBEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEqualActionPerformed
        arithmetic_operation();
        jTFOperation.setText("");
    }//GEN-LAST:event_jBEqualActionPerformed

    private void JBPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPlusActionPerformed
        try{
            num = Double.parseDouble(jTFDisplay.getText());
            calculation = 1;
            jTFDisplay.setText("");
            jTFOperation.setText(num + " + ");
        }catch(Exception e) {
            jTFDisplay.setText("Try again , Please Clock on C");
        }
    }//GEN-LAST:event_JBPlusActionPerformed

    private void jBMultipleTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMultipleTenActionPerformed
        try {
            double change = Double.parseDouble(String.valueOf(jTFDisplay.getText()));
            change = change *10;
            jTFDisplay.setText(String.valueOf(change));
        }catch(Exception e) {
            jTFDisplay.setText("Try again , Please Clock on C");
        }
    }//GEN-LAST:event_jBMultipleTenActionPerformed

    private void jBDoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDoteActionPerformed
        if (!jTFDisplay.getText().contains(".")) {
            String input = jTFDisplay.getText() + jBDote.getText();
            jTFDisplay.setText(input);
        }
    }//GEN-LAST:event_jBDoteActionPerformed

    private void jBZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBZeroActionPerformed
        jTFDisplay.setText(jTFDisplay.getText() + "0");
    }//GEN-LAST:event_jBZeroActionPerformed

    private void jBOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOneActionPerformed
        jTFDisplay.setText(jTFDisplay.getText() + "1");
    }//GEN-LAST:event_jBOneActionPerformed

    private void jBTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTwoActionPerformed
        jTFDisplay.setText(jTFDisplay.getText() + "2");
    }//GEN-LAST:event_jBTwoActionPerformed

    private void jBFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFourActionPerformed
        jTFDisplay.setText(jTFDisplay.getText() + "4");
    }//GEN-LAST:event_jBFourActionPerformed

    private void jBSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSevenActionPerformed
        jTFDisplay.setText(jTFDisplay.getText() + "7");
    }//GEN-LAST:event_jBSevenActionPerformed

    private void jBSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSqrtActionPerformed
        try{
            double change = Double.parseDouble(String.valueOf(jTFDisplay.getText()));
            change = Math.sqrt(change);
            jTFOperation.setText(String.valueOf(change));
            calculation = 7;
        }catch(Exception e) {
            jTFDisplay.setText("Try again , Please Clock on C");
        }
    }//GEN-LAST:event_jBSqrtActionPerformed

    private void jBMoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMoodActionPerformed
        try{
            num = Double.parseDouble(jTFDisplay.getText());
            calculation = 5;
            jTFDisplay.setText("");
            jTFOperation.setText(num + "%");
        }catch(Exception e) {
            jTFDisplay.setText("Try again , Please Clock on C");
        }
    }//GEN-LAST:event_jBMoodActionPerformed

    private void jBEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEightActionPerformed
        jTFDisplay.setText(jTFDisplay.getText() + "8");
    }//GEN-LAST:event_jBEightActionPerformed

    private void jBFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFiveActionPerformed
        jTFDisplay.setText(jTFDisplay.getText() + "5");
    }//GEN-LAST:event_jBFiveActionPerformed

    private void jBSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSixActionPerformed
        jTFDisplay.setText(jTFDisplay.getText() + "6");
    }//GEN-LAST:event_jBSixActionPerformed

    private void jBThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBThreeActionPerformed
        jTFDisplay.setText(jTFDisplay.getText() + "3");
    }//GEN-LAST:event_jBThreeActionPerformed

    private void jBSubstractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSubstractionActionPerformed
        try{
            num = Double.parseDouble(jTFDisplay.getText());
            calculation = 2;
            jTFDisplay.setText("");
            jTFOperation.setText(num + " - ");
        }catch(Exception e) {
            jTFDisplay.setText("Try again , Please Clock on C");
        }
    }//GEN-LAST:event_jBSubstractionActionPerformed

    private void jBSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSignActionPerformed
        try{
            double change = Double.parseDouble(String.valueOf(jTFDisplay.getText()));
            change = change * (-1);
            jTFDisplay.setText(String.valueOf(change));
        }catch(Exception e) {
            jTFDisplay.setText("Try again , Please Clock on C");
        }
    }//GEN-LAST:event_jBSignActionPerformed

    private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteActionPerformed
        int length = jTFDisplay.getText().length();
        int number = jTFDisplay.getText().length()-1;
        String Store;
        if(length > 0){
            StringBuilder Back = new StringBuilder(jTFDisplay.getText());
            Back.deleteCharAt(number);
            Store = Back.toString();
            jTFDisplay.setText(Store);
        }
    }//GEN-LAST:event_jBDeleteActionPerformed

    private void jBMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMultiplicationActionPerformed
        try{
            num = Double.parseDouble(jTFDisplay.getText());
            calculation = 3;
            jTFDisplay.setText("");
            jTFOperation.setText(num + " x ");
        }catch(Exception e) {
            jTFDisplay.setText("Try again , Please Clock on C");
        }
    }//GEN-LAST:event_jBMultiplicationActionPerformed

    private void jBDevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDevisionActionPerformed
        try{
            num = Double.parseDouble(jTFDisplay.getText());
            calculation = 4;
            jTFDisplay.setText("");
            jTFOperation.setText(num + " / ");
        }catch(Exception e) {
            jTFDisplay.setText("Try again , Please Clock on C");
        }
    }//GEN-LAST:event_jBDevisionActionPerformed

    private void jBClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClearActionPerformed
        jTFDisplay.setText(" ");
        jTFOperation.setText(" ");
    }//GEN-LAST:event_jBClearActionPerformed

    private void jBPowerOfXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPowerOfXActionPerformed
        try{
            double change = Double.parseDouble(String.valueOf(jTFDisplay.getText()));
            change = Math.pow(change, change);
            jTFOperation.setText(String.valueOf(change));
            calculation = 7;
        }catch(Exception e) {
            jTFDisplay.setText("Try again , Please Clock on C");
        }
    }//GEN-LAST:event_jBPowerOfXActionPerformed

    private void jBPowerOf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPowerOf3ActionPerformed
        try {
            double change = Double.parseDouble(String.valueOf(jTFDisplay.getText()));
            change = change * change * change;
            jTFOperation.setText(String.valueOf(change));
            calculation = 7;
        }catch(Exception e) {
            jTFDisplay.setText("Try again , Please Clock on C");
        }
    }//GEN-LAST:event_jBPowerOf3ActionPerformed

    private void jBPowerOf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPowerOf2ActionPerformed
        try {
            double change = Double.parseDouble(String.valueOf(jTFDisplay.getText()));
            change = change * change;
            jTFOperation.setText(String.valueOf(change));
            calculation = 7;
        }catch(Exception e) {
            jTFDisplay.setText("Try again , Please Clock on C");
        }
    }//GEN-LAST:event_jBPowerOf2ActionPerformed

    private void jBNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNineActionPerformed
        jTFDisplay.setText(jTFDisplay.getText() + "9");
    }//GEN-LAST:event_jBNineActionPerformed

    private void jRadioOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioOffActionPerformed
        disable();
    }//GEN-LAST:event_jRadioOffActionPerformed

    private void jRadioBOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBOnActionPerformed
        enable();
    }//GEN-LAST:event_jRadioBOnActionPerformed

    private void jBBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBinaryActionPerformed
        try{
            double a = Double.parseDouble(jTFDisplay.getText());
            jTFOperation.setText(Integer.toString((int) a, 2));
            calculation = 7;
        } catch(Exception e) {
            jTFDisplay.setText("Try again , Please Clock on C");
        }
    }//GEN-LAST:event_jBBinaryActionPerformed

    private void jBHexdecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHexdecimalActionPerformed
        try{
            double a = Double.parseDouble(jTFDisplay.getText());
            jTFOperation.setText(Integer.toString((int) a, 16));
        }catch(Exception e) {
            jTFDisplay.setText("Try again , Please Clock on C");
        }
    }//GEN-LAST:event_jBHexdecimalActionPerformed

    private void jBSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSinActionPerformed
        try {
            double change = Double.parseDouble(String.valueOf(jTFDisplay.getText()));
            change = Math.sin(change);
            jTFOperation.setText(String.valueOf(change));
            calculation = 7;
        }catch(Exception e) {
            jTFDisplay.setText("Try again , Please Clock on C");
        }
    }//GEN-LAST:event_jBSinActionPerformed

    private void jBCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCosActionPerformed
        try{
            double change = Double.parseDouble(String.valueOf(jTFDisplay.getText()));
            change = Math.cos(change);
            jTFOperation.setText(String.valueOf(change));
            calculation = 7;
        }catch(Exception e) {
            jTFDisplay.setText("Try again , Please Clock on C");
        }
    }//GEN-LAST:event_jBCosActionPerformed

    private void jBTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTanActionPerformed
        try{
            double change = Double.parseDouble(String.valueOf(jTFDisplay.getText()));
            change = Math.tan(change);
            jTFOperation.setText(String.valueOf(change));
            calculation = 7;
        }catch(Exception e) {
            jTFDisplay.setText("Try again , Please Clock on C");
        }
    }//GEN-LAST:event_jBTanActionPerformed

    private void jTFDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDisplayActionPerformed

    /**
     * @param args the command line arguments
     */
     private void setIcon(){
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon.png")));    
    } 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBPlus;
    private javax.swing.JMenu Quit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBBinary;
    private javax.swing.JButton jBClear;
    private javax.swing.JButton jBCos;
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBDevision;
    private javax.swing.JButton jBDote;
    private javax.swing.JButton jBEight;
    private javax.swing.JButton jBEqual;
    private javax.swing.JButton jBFive;
    private javax.swing.JButton jBFour;
    private javax.swing.JButton jBHexdecimal;
    private javax.swing.JButton jBMood;
    private javax.swing.JButton jBMultipleTen;
    private javax.swing.JButton jBMultiplication;
    private javax.swing.JButton jBNine;
    private javax.swing.JButton jBOne;
    private javax.swing.JButton jBPowerOf2;
    private javax.swing.JButton jBPowerOf3;
    private javax.swing.JButton jBPowerOfX;
    private javax.swing.JButton jBSeven;
    private javax.swing.JButton jBSign;
    private javax.swing.JButton jBSin;
    private javax.swing.JButton jBSix;
    private javax.swing.JButton jBSqrt;
    private javax.swing.JButton jBSubstraction;
    private javax.swing.JButton jBTan;
    private javax.swing.JButton jBThree;
    private javax.swing.JButton jBTwo;
    private javax.swing.JButton jBZero;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuOpen;
    private javax.swing.JMenuItem jMenuQuit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioBOn;
    private javax.swing.JRadioButton jRadioOff;
    private javax.swing.JTextField jTFDisplay;
    private javax.swing.JTextField jTFOperation;
    // End of variables declaration//GEN-END:variables
}
